Added All Ratings To Hall Pages. Changed Image Pop-up Button to Bootstrap.
coder13/cwu-rate-my-dorm pull request #38
Opened 2021-06-04 08:23 UTC by elimccoy

2021-06-04 20:18 UTC, acostana approved these changes
Looks good!

2021-06-04 20:48 UTC, crturnbull approved these changes
Looks good

2021-06-05 15:40 UTC, coder13 requested changes

2021-06-05 15:40 UTC, coder13 commented on src/Pages/ExampleHallPage.jsx
> +        this.setState({overallRatingTotal: dormResult[0]});
You can actually do all of these in a single setState.
Important thing to note because for each setState, react rebuilds the html. If it's one change with lots of parts, it should be a single setState with each property in a single object.

E.G.

```js
this.setState({
  overallRatingTotal: dormResult[0],
  locationRatingTotal: dormResult[1],
  roomSizeRatingTotal: dormResult[2],
  etc...
});
```

2021-06-08 20:46 UTC, elimccoy commented on src/Pages/ExampleHallPage.jsx
> +        this.setState({overallRatingTotal: dormResult[0]});
Fixed.

2021-06-08 20:59 UTC, coder13 approved these changes

2021-06-08 20:59 UTC, merged